package ejercicio01_MiCacharrito;

import javax.swing.JOptionPane;

/**
 *
 * @author Javier "KuaKer" Suárez Guzmán
 */
public class MiCacharrito extends javax.swing.JFrame {

    /**
     * Creates new form MiCacharrito
     */
    public MiCacharrito() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoVehículo = new javax.swing.ButtonGroup();
        panelTipoVehículo = new javax.swing.JPanel();
        tipoVehículo = new javax.swing.JLabel();
        rbtAutomóvil = new javax.swing.JRadioButton();
        rbtCamioneta = new javax.swing.JRadioButton();
        rbtCamión = new javax.swing.JRadioButton();
        panelCaracterísticas = new javax.swing.JPanel();
        características = new javax.swing.JLabel();
        cbCaracterísticas = new javax.swing.JComboBox<>();
        panelBotones = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelAccesorios = new javax.swing.JPanel();
        accesorios = new javax.swing.JLabel();
        cbAccesorios = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi Cacharrito: Presupuesto");

        panelTipoVehículo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tipoVehículo.setText("Tipo de Vehículo");

        grupoTipoVehículo.add(rbtAutomóvil);
        rbtAutomóvil.setText("Automóvil");

        grupoTipoVehículo.add(rbtCamioneta);
        rbtCamioneta.setText("Camioneta");

        grupoTipoVehículo.add(rbtCamión);
        rbtCamión.setText("Camión");

        javax.swing.GroupLayout panelTipoVehículoLayout = new javax.swing.GroupLayout(panelTipoVehículo);
        panelTipoVehículo.setLayout(panelTipoVehículoLayout);
        panelTipoVehículoLayout.setHorizontalGroup(
            panelTipoVehículoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoVehículoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelTipoVehículoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoVehículo, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(rbtAutomóvil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbtCamioneta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbtCamión, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        panelTipoVehículoLayout.setVerticalGroup(
            panelTipoVehículoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoVehículoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoVehículo)
                .addGap(12, 12, 12)
                .addComponent(rbtAutomóvil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtCamioneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtCamión)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCaracterísticas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        características.setText("Características");

        cbCaracterísticas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Básico ($0)", "Semi-Full", "Full Equipo" }));
        cbCaracterísticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCaracterísticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCaracterísticasLayout = new javax.swing.GroupLayout(panelCaracterísticas);
        panelCaracterísticas.setLayout(panelCaracterísticasLayout);
        panelCaracterísticasLayout.setHorizontalGroup(
            panelCaracterísticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaracterísticasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCaracterísticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(características)
                    .addComponent(cbCaracterísticas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        panelCaracterísticasLayout.setVerticalGroup(
            panelCaracterísticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaracterísticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(características)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCaracterísticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Nueva cotización");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        panelAccesorios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        accesorios.setText("Accesorios");

        cbAccesorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin accesorios", "Radio básica", "Full radio", "Full radio + LCD TV", "Full radio + LCD full", "Full radio + LCD full + Llantas" }));
        cbAccesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAccesoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAccesoriosLayout = new javax.swing.GroupLayout(panelAccesorios);
        panelAccesorios.setLayout(panelAccesoriosLayout);
        panelAccesoriosLayout.setHorizontalGroup(
            panelAccesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccesoriosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAccesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accesorios)
                    .addComponent(cbAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        panelAccesoriosLayout.setVerticalGroup(
            panelAccesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccesoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accesorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTipoVehículo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelCaracterísticas, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTipoVehículo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCaracterísticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAccesorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // solo debe mostrar el valor total
        calcularPresupuesto(1);

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // debe mostrar el detalle de cada item con sus precios y el total
        calcularPresupuesto(2);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        grupoTipoVehículo.clearSelection();
        cbCaracterísticas.setSelectedIndex(0);
        cbAccesorios.setSelectedIndex(0);

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cbCaracterísticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCaracterísticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCaracterísticasActionPerformed

    private void cbAccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAccesoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAccesoriosActionPerformed
    public void calcularPresupuesto(int opcion) {
        int aPagar = 0;
        double totalIVA = 0;
        boolean swTipoVehículo = true, swCaracteristicas = true, swAccesorios = true; //sw = switch
        String mensajeError = "Debe seleccionar:\n";
        // verificando el tipo de vehículo
        String detalle = "Detalle de la compra\n";
        if (rbtAutomóvil.isSelected()) {
            aPagar += 5000000;
            detalle += "$ 5.000.000.- Automóvil\n";
            swTipoVehículo = false;
        } else {
            if (rbtCamioneta.isSelected()) {
                aPagar += 8000000;
                detalle += "$ 8.000.000 - Camioneta\n";
                swTipoVehículo = false;
            } else {
                if (rbtCamión.isSelected()) {
                    aPagar += 12000000;
                    detalle += "$ 12.000.000.- Camión\n";
                    swTipoVehículo = false;
                } else {
                    // NO HA SELECCIONADO OPCIÓN
                    mensajeError += " - Tipo de vehículo\n";
                }
            }
        }
        // verificando las características
        int posItem = cbCaracterísticas.getSelectedIndex();
        if (posItem >= 0) {
            switch (posItem) {
                case 0: //básico
                    aPagar += 0; 
                    detalle += "$ 0.- Básico\n";
                    break;
                case 1: // semifull
                    aPagar += 500000;
                    detalle += "$ 500.000.- Semi-Full\n";
                    break;
                case 2: // fullequipo
                    aPagar += 1000000;
                    detalle += "$ 1.000.000.- Full Equipo\n";
                    break;
            }
            // verificando los accesoarios
            int posItem2 = cbAccesorios.getSelectedIndex();
            if (posItem2 >= 0) {
                switch (posItem2) {
                    case 0: //Sin accesorios
                        aPagar += 0;
                        detalle += "$ 0.- Sin accesorios\n";
                        break;
                    case 1: // Radio Básica
                        aPagar += 60000;
                        detalle += "$ 60.000.- Radio Básica\n";
                        break;
                    case 2: // Full Radio
                        aPagar += 100000;
                        detalle += "$ 100.000.- Full Radio\n";
                        break;
                    case 3: // Full Radio + LCD-TV
                        aPagar += 150000;
                        detalle += "$ 150.000.- Full Radio + LCD-TV\n";
                        break;
                    case 4: //Full Radio + LCD Full 
                        aPagar += 200000;
                        detalle += "$ 200.000.- Full Radio + LCD Full \n";
                        break;
                    case 5: //Full Radio + LCD Full + Llantas
                        aPagar += 500000; 
                        detalle += "$ 500.000.- Full Radio + LCD Full + Llantas\n";
                        break;
                }
            }
            totalIVA = (aPagar*1.19);
            int totalIVA2 = (int) totalIVA;
            detalle += "\n$ " + aPagar + ".- Sub total sin impuestos\n"
                    + "$ " + totalIVA2 + ".- Total + IVA\n";

            if (swTipoVehículo) {
                JOptionPane.showMessageDialog(null, mensajeError);
            } else {
                if (opcion == 1) {
                    JOptionPane.showMessageDialog(null, "Valor a pagar $ " + aPagar + ".-");
                }
                if (opcion == 2) {
                    JOptionPane.showMessageDialog(null, detalle);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiCacharrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiCacharrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiCacharrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiCacharrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiCacharrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accesorios;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel características;
    private javax.swing.JComboBox<String> cbAccesorios;
    private javax.swing.JComboBox<String> cbCaracterísticas;
    private javax.swing.ButtonGroup grupoTipoVehículo;
    private javax.swing.JPanel panelAccesorios;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCaracterísticas;
    private javax.swing.JPanel panelTipoVehículo;
    private javax.swing.JRadioButton rbtAutomóvil;
    private javax.swing.JRadioButton rbtCamioneta;
    private javax.swing.JRadioButton rbtCamión;
    private javax.swing.JLabel tipoVehículo;
    // End of variables declaration//GEN-END:variables
}
